name: Deploy
on:
  push: { branches: master }

jobs:
  test:
    name: Deploy docker images
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push base image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./docker/base
        push: true
        tags: |
          exaworks/sdk-base:latest
          ghcr.io/exaworks/sdk-base:latest
        platforms: linux/amd64

    - name: Build RP
      uses: docker/build-push-action@v2
      with:
        context: ./docker/rp
        push: false
        load: true
        platforms: linux/amd64
        tags: exaworks/rp

    - name: Build Parsl
      uses: docker/build-push-action@v2
      with:
        context: ./docker/Parsl
        push: false
        load: true
        platforms: linux/amd64
        tags: exaworks/rp_parsl
        build-args: |
          BASE_IMAGE=exaworks/rp

    - name: Build Swift
      uses: docker/build-push-action@v2
      with:
        context: ./docker/swift-t
        push: false
        load: true
        platforms: linux/amd64
        tags: exaworks/rp_parsl_swift
        build-args: |
          BASE_IMAGE=exaworks/rp_parsl

    - name: Build Flux
      uses: docker/build-push-action@v2
      with:
        context: ./docker/flux
        push: true
        platforms: linux/amd64
        tags: exaworks/sdk:latest
        build-args: |
          BASE_IMAGE=exaworks/rp_parsl_swift