name: Deploy
on:
  push: { branches: master }

jobs:
  test:
    name: Deploy docker images
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push base image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./docker/base
        push: true
        tags: |
          exaworks/sdk-base:latest
        platforms: linux/amd64

    - name: Build and push composite image
      run: |
        docker build -t rp docker/rp
        docker build -t rp_parsl --build-arg BASE_IMAGE=rp docker/Parsl
        docker build -t rp_parsl_swift --build-arg BASE_IMAGE=rp_parsl docker/swift-t
        docker build -t exaworks/sdk --build-arg BASE_IMAGE=rp_parsl_swift docker/flux
        docker push exaworks/sdk